// Generated by CIRCT firtool-1.62.1
module Descrambler(
  input        clock,
               reset,
               io_tx_enable,
               io_scn_0,
               io_scn_1,
               io_scn_2,
               io_scn_3,
               io_scn_4,
               io_scn_5,
               io_scn_6,
               io_scn_7,
               io_sdn_0,
               io_sdn_1,
               io_sdn_2,
               io_sdn_3,
               io_sdn_4,
               io_sdn_5,
               io_sdn_6,
               io_sdn_7,
               io_sdn_8,
               io_loc_rcvr_status,
  output [7:0] io_recovered_tx_data,
  output       io_recovered_tx_error
);

  reg        tx_enable_n_2_r;
  reg        tx_enable_n_2;
  wire       csreset = tx_enable_n_2 & ~io_tx_enable;
  wire       _tx_data_bits_2_T_2 = io_sdn_2 ^ io_scn_2;
  wire       cext_err_n = io_sdn_1 ^ io_scn_1;
  wire       cext_n = io_sdn_0 ^ io_scn_0;
  wire [7:0] io_recovered_tx_data_0 =
    {~csreset & tx_enable_n_2 & (io_sdn_7 ^ io_scn_7),
     ~csreset & tx_enable_n_2 & (io_sdn_6 ^ io_scn_6),
     tx_enable_n_2 & (io_sdn_5 ^ io_scn_5),
     tx_enable_n_2 & (io_sdn_4 ^ io_scn_4),
     tx_enable_n_2 & (io_sdn_3 ^ io_scn_3),
     tx_enable_n_2 ? _tx_data_bits_2_T_2 : io_loc_rcvr_status & ~_tx_data_bits_2_T_2,
     tx_enable_n_2 & cext_err_n,
     tx_enable_n_2 & cext_n};
  always @(posedge clock) begin
    if (reset) begin
      tx_enable_n_2_r <= 1'h0;
      tx_enable_n_2 <= 1'h0;
    end
    else begin
      tx_enable_n_2_r <= io_tx_enable;
      tx_enable_n_2 <= tx_enable_n_2_r;
    end
  end // always @(posedge)
  assign io_recovered_tx_data = io_recovered_tx_data_0;
  assign io_recovered_tx_error =
    ~io_tx_enable & io_recovered_tx_data_0 == 8'hF
      ? cext_n
      : ~io_tx_enable & io_recovered_tx_data_0 != 8'hF & cext_err_n;
endmodule


